Cleanup of project:create command and replacements

diff --git a/plugins/project/subcommands/create b/plugins/project/subcommands/create
--- a/plugins/project/subcommands/create
+++ b/plugins/project/subcommands/create
@@ -9,7 +9,10 @@ list_templates() {
     find $PLUGIN_PATH/project/templates -maxdepth 1 -type d -print | tail -n +2 | rev | cut -d'/' -f 1 | rev
 }
 
-build="gradle"
+_build="gradle"
+_template="war"
+_jee_version="7"
+
 
 usage() {
     templates=$(list_templates | paste -sd "|" -)
@@ -36,9 +39,8 @@ usage() {
 scaffold() {
     local groupid=$1
     local artifactid=$2
-    local template=$3
     
-    cp -r $PLUGIN_PATH/project/templates/$template $artifactid
+    cp -r $PLUGIN_PATH/project/templates/$_template $artifactid
 
     find $artifactid -type d -name "packagename" | while read dir; do
         # Derive packagenames from groupid/artifactid
@@ -73,13 +75,13 @@ scaffold() {
         touch .jeeez
     fi
 
-    if [[ "$build" == "maven" ]]; then
+    if [[ "$_build" == "maven" ]]; then
         rm -rf $artifactid/gradle
         rm -f $artifactid/gradlew*
         rm -f $artifactid/settings.gradle
         find $artifactid -type f -exec sed -i "s/template-artifactid/${artifactid}/g" {} \;
         find $artifactid -type f -name "build.gradle" -exec rm -f {} \;
-    elif [[ "$build" == "gradle" ]]; then
+    elif [[ "$_build" == "gradle" ]]; then
         rm -rf $artifactid/.mvn
         rm -f $artifactid/mvnw*
         find $artifactid -type f -name "pom.xml" -exec rm -f {} \;
@@ -87,44 +89,39 @@ scaffold() {
 
     if [[ "$artifactid" == *-st ]]; then
         # This is a system-test project
-        # Fint the main project this belongs to
-        parentid=${artifactid%-st}
-        if [ -d "$parentid" ]; then
-            parentpath=$(pwd)/$parentid
-            log_info "Found parent-project @ $parentpath"
-            #echo "PROJECT=$parentpath" >> $artifactid/.env
-            #echo "APPNAME=$parentid" >> $artifactid/.env
-            echo "COMPOSE_PROJECT_NAME=$parentid" >> $artifactid/.env
-            find $parentpath -type f -exec sed -i "s/@APPNAME@/${parentid}/g" {} \;
-            find $artifactid -type f -exec sed -i "s/@APPNAME@/${parentid}/g" {} \;
-            #find $artifactid -type f -name "docker-compose*.yml" -exec sed -i "s/@APPNAME@/${parentid}/g" {} \;
+        # Find the main project this belongs to
+        parent_artifactid=${artifactid%-st}
+        if [ -d "$parent_artifactid" ]; then
+            log_info "Found parent-project @ $parent_artifactid"
+            echo "COMPOSE_PROJECT_NAME=$parent_artifactid" >> $artifactid/.env
+            find $artifactid -type f -exec sed -i "s/template-parent-artifactid/${parent_artifactid}/g" {} \;
             
-            if [[ "$build" == "maven" ]]; then
+            if [[ "$_build" == "maven" ]]; then
                 find $artifactid -type f -exec sed -i "s/build\/libs/target/g" {} \;
             fi
             (
-                APPNAME=$parentid
+                APPNAME=$parent_artifactid
                 for composeFile in $artifactid/docker-compose*.yml; do
                     create_file_from_template $composeFile $composeFile
                 done
             )
         else
-            log_err "Expected a main-project named '$parentid' but unable to find."
+            log_err "Expected a main-project named '$parent_artifactid' but unable to find."
             exit 1
         fi
 
-        log_success "Succesfully created system-test project with artifact-id '$artifactid' and group-id '$groupid' from template '$template'."
+        log_success "Succesfully created system-test project with artifact-id '$artifactid' and group-id '$groupid' from template '$_template'."
         log_info $HR
-        if [[ "$build" == "maven" ]]; then
+        if [[ "$_build" == "maven" ]]; then
             log_info "Run them with 'cd $artifactid; ./mvnw verify'."
         else
             log_info "Run them with 'cd $artifactid; ./gradlew systemTestInDockerEnv'."
         fi
-        log_info "This project only works in conjunction with the project named '$parentid' located parallel to this project."
+        log_info "This project only works in conjunction with the project named '$parent_artifactid' located parallel to this project."
         log_info "Make sure to run  the build on it at least once to generate the artifact to deploy."
         log_info $HR
     else
-        log_success "Succesfully created a project with artifact-id '$artifactid' and group-id '$groupid' from template '$template'."
+        log_success "Succesfully created a project with artifact-id '$artifactid' and group-id '$groupid' from template '$_template'."
         log_info $HR
         log_info "Build & run it with 'cd $artifactid; ./run_docker.sh'."
         log_info "Open http://localhost/$artifactid/resources/health when the sever is started."
@@ -147,24 +144,24 @@ plugin_main_cmd() {
         exit 1
     fi
 
-    project_name=$1
+    local project_name=$1
     shift
 
     while [ $# -gt 0 ]; do
     case "$1" in
         --jee-version=*)
-        jee_version="${1#*=}"
+        _jee_version="${1#*=}"
         ;;
         --template=*)
-        template="${1#*=}"
+        _template="${1#*=}"
         ;;
         --st)
         # If we are generating a system-test project, append "-st" to project-name
         project_name="${project_name}-st"
-        template="st"
+        _template="st"
         ;;
         --build=*)
-        build="${1#*=}"
+        _build="${1#*=}"
         ;;
         *)
         log_err "Invalid argument"
@@ -172,19 +169,6 @@ plugin_main_cmd() {
     esac
     shift
     done
-
-    if [ -z "$template" ]; then
-        template="war"
-    fi
-
-    if [ -z "$jee_version" ]; then
-        jee_version="7"
-    fi
-
-    if [ -z "$jee_version" ]; then
-        jee_version="7"
-    fi
-
 
     if [[ $(expr index "$project_name" .) != "0" ]] ; then
         # project-name contains dot and thus a group-id
@@ -195,12 +179,12 @@ plugin_main_cmd() {
         artifactid="$project_name"
     fi
 
-    if ! [ -d $PLUGIN_PATH/project/templates/$template ]; then
-        log_err "No template with name '$template'"
+    if ! [ -d $PLUGIN_PATH/project/templates/$_template ]; then
+        log_err "No template with name '$_template'"
         exit 1
     fi
 
-    scaffold $groupid $artifactid $template
+    scaffold $groupid $artifactid
 }
 
 plugin_main_cmd "$@"
